spring.application.name=app6

#cau hinh co so du lieu
spring.datasource.url=jdbc:mysql://localhost:3306/promotiondb
spring.datasource.username=root
spring.datasource.password=12345678

#cau hinh hybernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
